version: '3.7'

services:
  liburanterus-frontend-react:
    container_name: liburanterus-frontend-react
    image: waziat/liburanterus-frontend-react:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    ports: 
      - 3009:3009
    restart: always
    networks:
      - liburanterus-microservices-networks
    working_dir: /user/app

networks:
  liburanterus-microservices-networks: 
    name: 'liburanterus-microservices-networks'
