name: Deploy to VPS

on:
  pull_request:
    branches: 
    - production

env:
  IMAGE_NAME: ${{ github.repository }}
  DOCKER_REPOSITORY: ${{ secrets.DOCKER_USERNAME }}
  TAG: ${{ github.run_number }}
  ENVIRONMENT: production
  DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
  HOSTS: ${{ secrets.VPS_HOST }}
  USERNAME: ${{ secrets.VPS_USERNAME }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm install

    - name: Run linting and unit tests
      run: npm test

    - name: Build React app
      run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3

    - name: Login with Github Container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Generate Docker metadata
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: |
          ghcr.io/$IMAGE_NAME
        tags: |
          type=ref,event=branch
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
        flavor: |
          latest=true

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # - name: Build Docker image
    #   run:  docker build . --file Dockerfile --tag ${{github.actor}}/$IMAGE_NAME:$ENVIRONMENT-$TAG
    
    # - name: Push Docker image
    #   run: docker push ghcr.io/${{github.actor}}/$IMAGE_NAME:$ENVIRONMENT-$TAG

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ghcr.io/$IMAGE_NAME:$ENVIRONMENT-$TAG

    - name: Set container image to private
      run: |
        curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -X PATCH -d '{"visibility":"private"}' https://ghcr.io/${{github.actor}}/$IMAGE_NAME:$ENVIRONMENT-$TAG/settings
    
    - name: multiple command
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: |
          whoami
          ls -al
          cd /var/www/auto-deploy-reactjs-server-vps
          ls
