name: production environment CI CD

on: 
  pull_request:
    branches: 
    - production
env:
  IMAGE_NAME: liburanterus-frontend-react
  DOCKER_REPOSITORY: ${{ secrets.DOCKER_USERNAME }}
  TAG: ${{ github.run_number }}
  ENVIRONMENT: production
  DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm install

    - name: Run linting and unit tests
      run: npm test

    - name: Build React app
      run: npm run build
  
  deploy:
    runs-on: ubuntu-latest
    
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ssh-key
        chmod 600 ssh-key
        echo "${{ secrets.SSH_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
        ssh-keyscan -H "${{ secrets.VPS_HOST }}" >> ~/.ssh/known_hosts

    - name: Build Docker image
      run: docker build . --file Dockerfile --tag $DOCKER_REPOSITORY/$IMAGE_NAME:latest

    - name: Deploy
      run: |
        scp -i ssh-key -r build/* "${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }}:/var/www/$IMAGE_NAME"
        ssh -i ssh-key "${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }}" <<EOF
        cd /var/www/$IMAGE_NAME
        docker-compose up -d --build
        EOF