name: Deploy to VPS

on:
  pull_request:
    branches: 
    - production

env:
  IMAGE_NAME: liburanterus-frontend-react
  DOCKER_REPOSITORY: ${{ secrets.DOCKER_USERNAME }}
  TAG: ${{ github.run_number }}
  ENVIRONMENT: production
  DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
  HOSTS: ${{ secrets.VPS_HOST }}
  USERNAME: ${{ secrets.VPS_USERNAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm install

    - name: Run linting and unit tests
      run: npm test

    - name: Build React app
      run: npm run build

    - name: Build Docker image
      run: |
        docker build . --file Dockerfile --tag waziat/liburanterus-frontend-react:$ENVIRONMENT-$TAG

    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: 103.13.206.22
        username: waziat
        password: Wanasaba10
        script: |
          docker stop $IMAGE_NAME || true
          docker rm $IMAGE_NAME || true
          docker run -d --name $IMAGE_NAME -p 3011:3000 $DOCKER_REPOSITORY/$IMAGE_NAME:$ENVIRONMENT-$TAG
